#! /bin/sh

# autostart "services"
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x mpd > /dev/null || mpd &
~/.config/polybar/launch.sh

# set desktop resolutions and wallpaper
xrandr --fbmm 7680x2160 --output DP-2 --pos 0x0 --mode 3840x2160 --scale 1x1 \
	--output HDMI-0 --pos 3840x0 --mode 2560x1440 --scale 1.5x1.5 --primary &
feh --no-fehbg --bg-fill --randomize ~/Pictures/Wallpapers/* &

# workspaces
bspc monitor DP-2 -d I II III IV V VI
bspc monitor HDMI-0 -d VII VIII

# general window settings
bspc config border_width            2
bspc config window_gap              32
bspc config split_ratio             0.6
bspc config focus_follows_pointer   false
bspc config borderless_monocle      true

# colors
bspc config normal_border_color     "#262335"
bspc config focused_border_color    "#ff7edb"
bspc config presel_feedback_color   "#fede5d"

# rules
bspc rule -a 'Brave-browser' desktop='^1' follow=on
bspc rule -a Postman desktop='^1' follow=on
bspc rule -a 'Microsoft Teams - Preview' desktop='^2' follow=on
bspc rule -a vlc desktop='^3' follow=on
bspc rule -a *:ncmpcpp desktop='^4' state=floating rectangle=1280x1200+2320+240 follow=on
bspc rule -a *:cava desktop='^4' state=floating rectangle=1280x448+2320+1472
bspc rule -a calibre desktop='^5' follow=on
bspc rule -a 'Tor Browser' desktop='^6' follow=on
bspc rule -a transmission desktop='^6'
