#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xrandr --output HDMI-0 --primary --mode 2560x1440 --pos 2560x0 --rotate normal --output DP-0 --off --output DP-1 --off --output DP-2 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off &
feh --no-fehbg --bg-fill --randomize ~/Pictures/wallpapers/* &
dunst &
~/.config/polybar/launch.sh

bspc monitor HDMI-0 -d VI VII VIII IX X
bspc monitor DP-2 -d I II III IV V

bspc config border_width            0
bspc config window_gap              16
bspc config split_ratio             0.6

bspc rule -a 'Brave-browser' desktop='^1'
bspc rule -a 'VirtualBox Manager' state=floating
bspc rule -a MPlayer desktop='^5' center=true follow=on rectangle=1280x720+640+360

#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a qBittorrent desktop='^7' state=floating center=true rectangle=1376x625+0+0
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
