#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xrandr --fbmm 7680x2160 --output DP-2 --pos 0x0 --mode 3840x2160 --scale 1x1 \
	--output HDMI-0 --pos 3840x0 --mode 2560x1440 --scale 1.5x1.5 --primary &
feh --no-fehbg --bg-fill --randomize ~/Pictures/Wallpapers/* &
dunst &
~/.config/polybar/launch.sh

# workspaces
bspc monitor DP-2 -d I II III IV V
bspc monitor HDMI-0 -d VI VII

# general window settings
bspc config border_width            2
bspc config window_gap              32
bspc config split_ratio             0.6
bspc config focus_follows_pointer   false
bspc config borderless_monocle      true

# colors
bspc config normal_border_color     "#262335"
bspc config focused_border_color    "#ff7edb"
bspc config presel_feedback_color   "#fede5d"

# rules
bspc rule -a 'Tor Browser' desktop '^5' follow=on
bspc rule -a transmission desktop='^5'

#bspc rule -a 'Brave-browser' desktop='^1'
#bspc rule -a 'VirtualBox Manager' state=floating
#bspc rule -a MPlayer desktop='^5' center=true follow=on rectangle=1280x720+640+360

#bspc rule -a qBittorrent desktop='^7' state=floating center=true rectangle=1376x625+0+0
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
